### ISSUE TITLE
Onnx export for the inference

### ISSUE THREAD

**Issue by llmexperiment** [alxndrTL/mamba.py#14]
Hi Alex,

I have tried to generate the onnx file for the inference, 
as follows in generate function.  

I called onnx export inside generate function here:  https://github.com/alxndrTL/mamba.py/blob/main/mamba_lm.py#L134 

as follows: 

torch.onnx.export(model, inputids, "mamba.onnx", opset_version=12)

It is throwing me an error 

TypeError:  MambaLM.forward() missing 1 required positional argument: 'tokens'.

Any idea how can I generate onnx file? Is there a better way of generating onnx file for inference?

**Comment by alxndrTL** [comment]
Hello, I haven't tried converting a Mamba model to ONNX, but it should be feasible (i'm not familiar with ONNX).

It's a bit particular with Mamba because for inference, you typically want to use the `step` function rather than the `forward` (it works using `forward`, but is much slower).
It seems it automatically tries to go with `forward`, but still it crashes...

When I see resources online, they use :
```
torch.onnx.dynamo_export(torch_model, torch_input)
onnx_program.save("my_image_classifier.onnx")
```

I will look into it when I have time.
Maybe you can try :
-see what's causing the problem when saving the `forward`
-to save the `step` function, I think you should rewrite the MambaLM and put the code in the `step` function inside the `forward` or something like that... because it seems it automatically saves what's in the `forward` function..

**Comment by llmexperiment** [comment]
Hi Alex
Tried different ways, but still it is going to "forward" function, and somehow could not generate onnx file yet.  

Besides, I also tried following, and it is going to the "forward function" and giving the following error. Any chance that you had  the opportunity to look into?  

` torch.onnx.export(model, {"input_ids":input_ids}, "temp_mamba.onnx", verbose=True)` ==> This goes to forward function. 

> Hello, I haven't tried converting a Mamba model to ONNX, but it should be feasible (i'm not familiar with ONNX).
> 
> It's a bit particular with Mamba because for inference, you typically want to use the `step` function rather than the `forward` (it works using `forward`, but is much slower). It seems it automatically tries to go with `forward`, but still it crashes...
> 
> When I see resources online, they use :
> 
> ```
> torch.onnx.dynamo_export(torch_model, torch_input)
> onnx_program.save("my_image_classifier.onnx")
> ```
> 
> I will look into it when I have time. Maybe you can try : -see what's causing the problem when saving the `forward` -to save the `step` function, I think you should rewrite the MambaLM and put the code in the `step` function inside the `forward` or something like that... because it seems it automatically saves what's in the `forward` function..

**Comment by Zeng-WCh** [comment]
Hello, I just implemented a relatively simple code to export to an ONNX model following your method. You can check it out in my code repository. However, I am not sure if it works correctly or how to evaluate its performance, as I am not very familiar with these aspects.

**Comment by Zeng-WCh** [comment]
Hi, I revisited the task and have successfully completed a basic version of ONNX exportation and usage. It appears to be functioning properly. You can review my changes in [my forked version](https://github.com/Zeng-WCh/mamba.py).

**Comment by alxndrTL** [comment]
Hello, thank you for your work! I saw you proposed a PR, I will take a look at it!

**Comment by alxndrTL** [comment]
Thanks to @Zeng-WCh, this issue is now closed :)
See [the PR](https://github.com/alxndrTL/mamba.py/pull/34) for more details.
